### ISSUE TITLE
Codon Wpf without NavigationWindow

### ISSUE THREAD

**Issue by adospace** [CalciumFramework/Calcium#15]
Hi,
I'm using Codon to build a small Visual Studio extensions in WPF.
A couple of questions:
1) I need to derive my main window class from a type other than NavigationWindow, is this possible? seems like that Codon force everything inside a Frame?
2) Can I completely remove the navigation system as it's not required in my case?

Thanks,
Ado

BTW Great work!

**Comment by DVaughan** [comment]
1. Yes, it can derive from whatever you like. The Codon's NavigationService for WPF looks for a System.Windows.Navigation.NavigationWindow, if it can't find it, it falls back to find a Frame.
2. Yes. If you don't attempt to resolve INavigationService from the IoC container, then the NavigationService is not instantiated and it not used.

**Comment by adospace** [comment]
Got it, thanks for your prompt reply.
