### ISSUE TITLE
Exception for Android application with linker option "sdk and user assemblies"

### ISSUE THREAD

**Issue by abrasat** [CalciumFramework/Calcium#22]
The following exception is thrown whan starting a Android application (from Xamarin.Forms project) with linker option "sdk and user assemblies", which references a NetStandard 2.0 class library using the Codon package,

Unhandled Exception:

Codon.InversionOfControl.ResolutionException: Interface type Microsoft.Extensions.Logging.ILoggerFactory has no registered type mapping, nor is there a default type mapping.

**Comment by DVaughan** [comment]
This looks unrelated to Codon.
Codon doesn't use a class implementing ILoggerFactory. I'd say you'll need to add an exclusion to prevent the linker from stripping the class that implements ILoggerFactory. See the Xamarin docs for that.
