### ISSUE TITLE
Enhancement Request : Option to configure IOC container

### ISSUE THREAD

**Issue by Shivashankar-N** [CalciumFramework/Calcium#26]
Would it be possible to provide an option to pass an IOC container  to Codon Dependency , so that we will have flexibility to use existing IOC container to resolve the dependency .

For example, we can implement IContainer and create a custom container class which can be injected to Dependecny instead of using FrameworkContainer. If there is an option to pass IOC Container, we could pass custom container object .

**Comment by DVaughan** [comment]
Yes, you can replace the `Codon.InversionOfControl.IContainer` implementation. 
You do this by implementing `Codon.InversionOfControl.IContainer` to wrap whatever library you want to use. At application startup call the `IContainer` extension method `ContainerExtensions.InitializeContainer`. That causes Codon to use your `IContainer` internally.

There are, however, several implicit type registrations that are handled by the built-in `FrameworkContainer`, which has the benefit that Codon doesn't need to be initialized. These implicit registrations are defined via attributes.
For example, some types, such as the `IDialogService`, are decorated with a `DefaultTypeNameAttribute`, which allows the built-in `FrameworkContainer` to automatically resolve types in platform specific assemblies.

So, along with the `IContainer` initialization, you would need to manually perform type registrations for all Codon types decorated with any of the following attributes:

* `Codon.InversionOfControl.DefaultTypeNameAttribute`
* `Codon.InversionOfControl.DefaultTypeAttribute`
* `System.ComponentModel.DefaultValueAttribute` 

Just do a search for '[DefaultTypeName' etc. There are about 20.

If you do create an `IContainer`, let me know and I'll try to roll these registrations into `ContainerExtensions.InitializeContainer`
