### ISSUE TITLE
NavigationService - how to check that target RelativeUrl is identical with current page ?

### ISSUE THREAD

**Issue by abrasat** [CalciumFramework/Calcium#6]
Is it possible to prevent navigation to a page (call to Navigate() from NavigationService), when that page is the same as the current page ?
I am using ItemTapped event to send a command (over a "eventtocommand" behavior) to a view model, where the Navigate() method is called to get to go to the detail page. If a item is tapped twice, the application navigates further to the detail page, although already on the detail page (the detail page is present twice in the navigation stack). Can this behavior be avoided, by adding an option to the NavigationService that blocks the navigation to a page, if that page is already the current page ?

**Comment by DVaughan** [comment]
There may be times when navigating to a new instance of the same page is valid.
There isn't that capability within the current implementations of the INavigationService for the various platforms. I can't see anything that would prevent it being implemented in each of the implementations. I'll take this as a feature request.
