### ISSUE TITLE
Codon.InversionOfControl exception when executing UWP application generated as release build

### ISSUE THREAD

**Issue by abrasat** [CalciumFramework/Calcium#9]
When executing the FormsStarter sample ( [https://github.com/CodonFramework/Samples/issues/2](https://github.com/CodonFramework/Samples/issues/2) , the one from 28.April), following exception occurs when the application is generated as release build and executed on a Windows 10 local machine. If application is generated as debug build, all works fine.

``
Codon.InversionOfControl.ResolutionException occurred
  HResult=0x80131500
  Message=Failed to resolve CodonXamarinFormsStarter.Page1ViewModel
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>
Inner Exception 1:
ArgumentException: Cannot reference type System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e in this context

**Comment by DVaughan** [comment]
It appears to be an issue with the native compilation that occurs as part of a release build.
I've added a workaround that appears to have resolved the issue. The fix is committed and present in the 2.0.7-alpha release.
